#!/usr/bin/env bash

if [ "$#" -ne 0 ] && [ "$#" -ne 1 ]; then
    echo "Usage: './new_game_omniscient' OR './new_game_omniscient -d (play_with_auto_dice)'"
fi

if [ "$#" -eq 0 ]; then
    python3 start_game.py -o
fi

if [ "$#" -eq 1 ]; then
    if [ "$1" != "-d" ]; then
        echo "Usage: './new_game_omniscient' OR './new_game_omniscient -d (play_with_auto_dice)'"
    fi
    python3 start_game.py -d -o
fi
