#!/usr/bin/env bash

echo "Command Options:"
echo "./setup (Download required dependencies for the game. Do this if you get any '<module> not found errors.')"
echo "./pull_updates (Pull any recently deployed game updates)')"
echo "./use_beta (Use the beta version of the game)')"
echo "./use_official (Use the official released version of the game)')"
echo ""

echo "./new_game (Starts a new game)"
echo "./new_game_omniscient (Starts a new game in omniscient mode)"
echo ""

echo "./restore_game <game_id> (Restores a game from its game id)"
echo "./restore_game_omniscient <game_id> (Restores a game from its game id in omniscient mode)"
echo ""

echo "./add_game_to_favorites <game_config> <unique_key> (Add a game to the favorites list)"
echo "./new_game_from_favorites <favorite_game_key> (Start a new game from a unique favorite game key)"
echo "./new_game_from_favorites_omniscient <favorite_game_key> (Start a new game from a unique favorite game key in omniscient mode)"
echo "./delete_favorited_game <unique_key> (Deletes a game from the favorites list)"
echo ""

echo "./delete_saved_game <game_id> (Deletes a saved game)"
echo "./delete_all_saved_games (Deletes all saved games)"
echo ""

echo "./list_saved_games (Lists all saved game ids)"
echo "./list_favorites (Lists all favorited games and their ids)"
echo ""

echo "(Below this is for development purposes only.)"
echo "./auto_play_new_game_omniscient (Auto plays an entire game with players acting and random computers)"
echo "./auto_play_new_game_from_favorites_omniscient <favorite_game_key> (Auto plays an entire game restored from favorites with players acting and random computers)"
echo ""
