#!/usr/bin/env bash

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "Usage: './restore_game <game_id>' OR './restore_game <game_id> -d (play_with_auto_dice)'"
fi

if [ "$#" -eq 1 ]; then
    python3 start_game.py -r $1
fi

if [ "$#" -eq 2 ]; then
    if [ "$2" != "-d" ]; then
        echo "Usage: './restore_game <game_id>' OR './restore_game <game_id> -d (play_with_auto_dice)'"
    fi
    python3 start_game.py -r $1 -d
fi
